[package]
name = "shim-release"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sv-parser = "0.11.3"
crc = "3.0.0"
env_logger = "0.9.0"
log = "0.4.0"
